services:
  dw-mongodb:
    image: "mongodb/mongodb-community-server:latest"
    container_name: "mongodb-latest"
    ports:
      - "27168:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwer
    volumes:
      - mongodb_latest_data_vol:/data/db/
      - mongodb_latest_log_vol:/var/log/mongodb/
    networks:
      - dw-net
volumes:
  mongodb_latest_data_vol:
  mongodb_latest_log_vol:
networks:
  dw-net:
    external: true
